
package ru.rt.fsom.wfc.data.oms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://oms.rt.ru/")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, TFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, TFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.rt.oms.TFault
     */
    public TFault getFaultInfo() {
        return faultInfo;
    }

}
