
package ru.rt.fsom.wfc.data.oms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OMSWebService", targetNamespace = "http://oms.rt.ru/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OMSWebService {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.rt.oms.SubmitOrderResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "submitOrderResponse", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
    public SubmitOrderResponse submitOrder(
        @WebParam(name = "submitOrderRequest", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
        SubmitOrderRequest parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.rt.oms.CancelOrderResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "cancelOrderResponse", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
    public CancelOrderResponse cancelOrder(
        @WebParam(name = "cancelOrderRequest", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
        CancelOrderRequest parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.rt.oms.AmendOrderResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "amendOrderResponse", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
    public AmendOrderResponse amendOrder(
        @WebParam(name = "amendOrderRequest", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
        AmendOrderRequest parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ru.rt.oms.QueryOrderResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "queryOrderResponse", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
    public QueryOrderResponse queryOrder(
        @WebParam(name = "queryOrderRequest", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
        QueryOrderRequest parameters)
        throws Fault
    ;

}
