
package ru.rt.fsom.wfc.data.oms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OMSWebService", targetNamespace = "http://oms.rt.ru/", wsdlLocation = "file:/C:/javawork/InstantLink/BSS_TO_IL/src/wsdl/RTFFAPI_v01.wsdl")
public class OMSWebService_Service
    extends Service
{

    private final static URL OMSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException OMSWEBSERVICE_EXCEPTION;
    private final static QName OMSWEBSERVICE_QNAME = new QName("http://oms.rt.ru/", "OMSWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/javawork/InstantLink/BSS_TO_IL/src/wsdl/RTFFAPI_v01.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OMSWEBSERVICE_WSDL_LOCATION = url;
        OMSWEBSERVICE_EXCEPTION = e;
    }

    public OMSWebService_Service() {
        super(__getWsdlLocation(), OMSWEBSERVICE_QNAME);
    }

    public OMSWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OMSWEBSERVICE_QNAME, features);
    }

    public OMSWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, OMSWEBSERVICE_QNAME);
    }

    public OMSWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OMSWEBSERVICE_QNAME, features);
    }

    public OMSWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OMSWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OMSWebService
     */
    @WebEndpoint(name = "OMSWebServicePort")
    public OMSWebService getOMSWebServicePort() {
        return super.getPort(new QName("http://oms.rt.ru/", "OMSWebServicePort"), OMSWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OMSWebService
     */
    @WebEndpoint(name = "OMSWebServicePort")
    public OMSWebService getOMSWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oms.rt.ru/", "OMSWebServicePort"), OMSWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OMSWEBSERVICE_EXCEPTION!= null) {
            throw OMSWEBSERVICE_EXCEPTION;
        }
        return OMSWEBSERVICE_WSDL_LOCATION;
    }

}
